### ISSUE TITLE
can not get card image because card is null

### ISSUE THREAD

**Issue by daiarn** [daiarn/UNO#32] opened 2019-11-16 21:34 UTC
```
private void HandPanel_Paint(object sender, PaintEventArgs e)
{
	if (Game != null)
	{
		var widthPerCard = HandCardWidth / 2;
		var handCount = Game.Gamestate.Hand.Count;

		var graphics = e.Graphics;
		float movePosition = 0f;
		xyImage = new float[handCount, 2];

		float width = (float) handPanel.Width;
		float height = (float) handPanel.Height;
		float middlePoint = width / 4f;

		if (handCount * widthPerCard > (width - middlePoint))
		{
			middlePoint = width - (handCount * widthPerCard);

			if (middlePoint < 0)
			{
				middlePoint = 0;
				widthPerCard = width / handCount;
			}
		}

		for (int i = 0; i < handCount; i++)
		{
			var card = Game.Gamestate.Hand[i];
			var img = card.GetImage();//Null pointer exception here

			xyImage[i, 0] = middlePoint + movePosition;
			xyImage[i, 1] = 15f; //Recommended cards
			movePosition += widthPerCard;

			var dbWidth = HandCardWidth / (float) img.Width;
			var dbHeight = dbWidth * img.Height;

			graphics.DrawImage(img, new RectangleF(xyImage[i, 0], xyImage[i, 1], HandCardWidth, dbHeight));
		}
	}
}
```
@MrRytis kiek žinau čia tu darei. Turi sipratimo kodėl taip? Gal ne naujas žaidėjo hand? Thread sleep needed? xD

**Comment by MrRytis** [comment] 2019-11-17 15:01
cannot reproduce. Everything works on my machine. Add more details if issue persist

**Comment by daiarn** [comment] 2019-11-17 15:02
I saw you added if statement to check if card is null. Maybe it is fixed now

**Comment by MrRytis** [comment] 2019-11-17 15:04
I'm closing issue

**Closed as completed by MrRytis** 2019-11-17 15:04 UTC
